### ISSUE TITLE
Error: Call PluginError using new

### ISSUE THREAD

**Issue by pixelshaded** [koemei/gulp-node-inspector#12]
```
var gulp = require('gulp');
var nodeInspector = require('gulp-node-inspector');
var cfg = require('../src/precompile/asset-config');

var taskName = 'node-inspector';
var nodeInspectorConfig = {
  webPort: 8080,
  webHost: 'localhost',
  debugPort: cfg.nodemon.debugPort,
  saveLiveEdit: true,
  hidden: ['node_modules']
};

gulp.task(taskName, function(callback){
  gulp.src([])
    .pipe(nodeInspector(nodeInspectorConfig));
});
```

Should be a simple fix on the emit 'error' event on line 34 of index.js.

```
Error: Call PluginError using new
    at PluginError (C:\repo\IgnitionOne\stable\prototype-coresettings\node_modules\gulp-util\lib\PluginError.js:33:45)
    at DebugServer.<anonymous> (C:\repo\IgnitionOne\stable\prototype-coresettings\node_modules\gulp-node-inspector\index.js:34:28)
    at DebugServer.emit (events.js:107:17)
    at DebugServer.handleServerError (C:\repo\IgnitionOne\stable\prototype-coresettings\node_modules\gulp-node-inspector\node_modules\node-inspector\lib\debug-server.js:32:8)
    at WebSocketServer.emit (events.js:107:17)
    at Server.<anonymous> (C:\repo\IgnitionOne\stable\prototype-coresettings\node_modules\gulp-node-inspector\node_modules\node-inspector\node_modules\ws\lib\WebSocketServer.js:65:12)
    at Server.emit (events.js:129:20)
    at net.js:1114:14
    at process._tickDomainCallback (node.js:381:11)
```

**Comment by Venegrad** [comment]
same error but with tiny-png
