### ISSUE TITLE
TypeError: Cannot call method 'on' of undefined

### ISSUE THREAD

**Issue by ruchevits** [koemei/gulp-node-inspector#7]
Simplest task:

	var $ = require('gulp-load-plugins')({lazy: true});
	gulp.task('debug', function() {
	  gulp
		.src('')
		.pipe($.nodeInspector());
	});

Fails with the following error:

	[19:04:52] Using gulpfile D:\AngularFullstack\Gulpfile.js
	[19:04:52] Starting 'debug'...
	[19:04:52] 'debug' errored after 80 ms
	[19:04:52] TypeError: Cannot call method 'on' of undefined
		at DestroyableTransform.Readable.pipe (D:\AngularFullstack\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:516:8)
		at Gulp.gulp.task.nodemonOptions.script (D:\AngularFullstack\Gulpfile.js:201:6)
		at module.exports (D:\AngularFullstack\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
		at Gulp.Orchestrator._runTask (D:\AngularFullstack\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
		at Gulp.Orchestrator._runStep (D:\AngularFullstack\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
		at Gulp.Orchestrator.start (D:\AngularFullstack\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
		at C:\Users\Edward\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
		at process._tickCallback (node.js:442:13)
		at Function.Module.runMain (module.js:499:11)
		at startup (node.js:119:16)

Could anyone please advice how to fix this?

**Comment by vohtaski** [comment]
I guess you are using the sample from master branch against the previous release.
Will push new release to npm soon, sorry for that

**Comment by vohtaski** [comment]
push version 0.0.2 to npm
could you pls try the latest version

**Comment by ruchevits** [comment]
Thank you for the quick response, works now.
